GPU Prolog Script v0.30
This is a GPU node.
Enough GPUs available.
Allocating card 0
gonzo-605-16.local
Thu 21 Jan 05:53:17 GMT 2021
2021-01-21 05:53:19.119034: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:Log directory logs/test exists already.
2021-01-21 05:53:23.381638: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-01-21 05:53:23.424740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: TITAN X (Pascal) computeCapability: 6.1
coreClock: 1.531GHz coreCount: 28 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 447.48GiB/s
2021-01-21 05:53:23.424789: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-21 05:53:23.428571: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-21 05:53:23.430884: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-21 05:53:23.431688: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-21 05:53:23.434729: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-21 05:53:23.437177: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-21 05:53:23.443238: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-21 05:53:23.445530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-01-21 05:53:23.461634: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-21 05:53:23.483308: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2095135000 Hz
2021-01-21 05:53:23.485767: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5e12c40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-21 05:53:23.485802: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-21 05:53:23.667624: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5e7f230 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-21 05:53:23.667667: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN X (Pascal), Compute Capability 6.1
2021-01-21 05:53:23.669283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: TITAN X (Pascal) computeCapability: 6.1
coreClock: 1.531GHz coreCount: 28 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 447.48GiB/s
2021-01-21 05:53:23.669348: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-21 05:53:23.669394: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-21 05:53:23.669421: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-21 05:53:23.669447: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-21 05:53:23.669474: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-21 05:53:23.669499: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-21 05:53:23.669535: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-21 05:53:23.672221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-01-21 05:53:23.672278: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-21 05:53:24.310573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-21 05:53:24.310632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-01-21 05:53:24.310642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2021-01-21 05:53:24.313744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11230 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
2021-01-21 05:53:26.888387: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2021-01-21 05:53:26.888433: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 1 GPUs
2021-01-21 05:53:26.888632: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /share/apps/cuda-10.1/lib64:/share/apps/gcc-8.3/lib64:/share/apps/python-3.7.2-shared/lib:/opt/gridengine/lib/lx-amd64
2021-01-21 05:53:26.889496: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcupti.so
2021-01-21 05:53:27.054095: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... 
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... 
2021-01-21 05:58:37.254622: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 1 of 2
2021-01-21 05:59:21.274489: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
2021-01-21 05:59:40.369653: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-21 05:59:43.768301: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
Epoch 1/10
 1/32 [..............................] - ETA: 0s - loss: -0.0642 - loss/regularization: 0.0000e+00 - loss/weighted_regularization: 0.0000e+00 - loss/image_dissimilarity: -0.6417 - loss/weighted_image_dissimilarity: -0.06422021-01-21 05:59:44.277682: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
WARNING:tensorflow:From /home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
WARNING:tensorflow:From /home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
2021-01-21 06:01:39.554617: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
2021-01-21 06:01:39.625422: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 3574 callback api events and 3574 activity events. 
2021-01-21 06:01:39.901415: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: logs/test/train/plugins/profile/2021_01_21_06_01_39
2021-01-21 06:01:40.027336: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for trace.json.gz to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.trace.json.gz
2021-01-21 06:01:40.202567: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: logs/test/train/plugins/profile/2021_01_21_06_01_39
2021-01-21 06:01:40.213674: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for memory_profile.json.gz to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.memory_profile.json.gz
2021-01-21 06:01:40.280875: I tensorflow/python/profiler/internal/profiler_wrapper.cc:111] Creating directory: logs/test/train/plugins/profile/2021_01_21_06_01_39Dumped tool data for xplane.pb to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.xplane.pb
Dumped tool data for overview_page.pb to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.overview_page.pb
Dumped tool data for input_pipeline.pb to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to logs/test/train/plugins/profile/2021_01_21_06_01_39/gonzo-605-16.local.kernel_stats.pb

 2/32 [>.............................] - ETA: 29:00 - loss: -0.0626 - loss/regularization: 5.6281e-09 - loss/weighted_regularization: 2.8140e-09 - loss/image_dissimilarity: -0.6258 - loss/weighted_image_dissimilarity: -0.0626 3/32 [=>............................] - ETA: 25:29 - loss: -0.0644 - loss/regularization: 1.5386e-08 - loss/weighted_regularization: 7.6928e-09 - loss/image_dissimilarity: -0.6444 - loss/weighted_image_dissimilarity: -0.06442021-01-21 06:05:48.802258: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 278, in data_generator
    moving_image = self.loader_moving_image.get_data(index=moving_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


Traceback (most recent call last):
  File "/home/bryanko/venvs/deepreg/bin/deepreg_train", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_train')())
  File "/home/bryanko/DeepReg/deepreg/train.py", line 256, in main
    max_epochs=args.max_epochs,
  File "/home/bryanko/DeepReg/deepreg/train.py", line 177, in train
    callbacks=callbacks,
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 278, in data_generator
    moving_image = self.loader_moving_image.get_data(index=moving_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


	 [[{{node PyFunc}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[div_no_nan_1/ReadVariableOp/_226]]
  (1) Unknown:  error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 278, in data_generator
    moving_image = self.loader_moving_image.get_data(index=moving_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


	 [[{{node PyFunc}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_24071]

Function call stack:
train_function -> train_function

Thu 21 Jan 06:05:52 GMT 2021
GPU Epilog Script v0.30
