GPU Prolog Script v0.30
This is a GPU node.
Enough GPUs available.
Allocating card 0
ernie.local
Tue 22 Dec 17:07:52 GMT 2020
2020-12-22 17:08:09.556902: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:Log directory logs/test exists already.
2020-12-22 17:08:27.766871: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-12-22 17:08:27.814588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:5e:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-12-22 17:08:27.814623: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-22 17:08:28.268176: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-22 17:08:28.652462: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-22 17:08:28.709564: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-22 17:08:29.177499: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-22 17:08:29.426126: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-22 17:08:30.555057: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-22 17:08:30.557648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-22 17:08:30.574154: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-22 17:08:30.620045: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3600000000 Hz
2020-12-22 17:08:30.620812: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x464bd80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-22 17:08:30.620860: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-22 17:08:30.754616: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x464e900 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-22 17:08:30.754676: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2020-12-22 17:08:30.805247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:5e:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-12-22 17:08:30.805314: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-22 17:08:30.805359: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-22 17:08:30.805384: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-22 17:08:30.805408: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-22 17:08:30.805431: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-22 17:08:30.805454: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-22 17:08:30.805484: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-22 17:08:30.807729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-22 17:08:30.809581: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-22 17:08:35.480771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-22 17:08:35.480915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-22 17:08:35.480929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-12-22 17:08:35.482928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7260 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:5e:00.0, compute capability: 7.5)
2020-12-22 17:08:38.493861: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-12-22 17:08:38.493905: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 1 GPUs
2020-12-22 17:08:38.495305: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /share/apps/cuda-10.1/lib64:/share/apps/gcc-8.3/lib64:/share/apps/python-3.7.2-shared/lib:/opt/gridengine/lib/lx-amd64
2020-12-22 17:08:38.515140: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcupti.so
2020-12-22 17:08:38.683179: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... 
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... 
2020-12-22 17:09:12.824693: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 1 of 2
2020-12-22 17:09:34.854646: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
2020-12-22 17:09:52.249495: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-22 17:10:02.226143: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
Epoch 1/2
 1/32 [..............................] - ETA: 0s - loss: -0.0540 - loss/regularization: 0.0000e+00 - loss/weighted_regularization: 0.0000e+00 - loss/image_dissimilarity: -0.5395 - loss/weighted_image_dissimilarity: -0.05402020-12-22 17:10:04.104613: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
WARNING:tensorflow:From /home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
WARNING:tensorflow:From /home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
2020-12-22 17:10:21.467908: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
2020-12-22 17:10:21.502246: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 2407 callback api events and 2407 activity events. 
2020-12-22 17:10:21.609285: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: logs/test/train/plugins/profile/2020_12_22_17_10_21
2020-12-22 17:10:21.652364: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for trace.json.gz to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.trace.json.gz
2020-12-22 17:10:21.731066: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: logs/test/train/plugins/profile/2020_12_22_17_10_21
2020-12-22 17:10:21.737909: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for memory_profile.json.gz to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.memory_profile.json.gz
2020-12-22 17:10:21.764229: I tensorflow/python/profiler/internal/profiler_wrapper.cc:111] Creating directory: logs/test/train/plugins/profile/2020_12_22_17_10_21Dumped tool data for xplane.pb to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.xplane.pb
Dumped tool data for overview_page.pb to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.overview_page.pb
Dumped tool data for input_pipeline.pb to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to logs/test/train/plugins/profile/2020_12_22_17_10_21/ernie.local.kernel_stats.pb

 2/32 [>.............................] - ETA: 4:25 - loss: -0.0578 - loss/regularization: 7.5880e-09 - loss/weighted_regularization: 3.7940e-09 - loss/image_dissimilarity: -0.5779 - loss/weighted_image_dissimilarity: -0.0578 3/32 [=>............................] - ETA: 8:28 - loss: -0.0616 - loss/regularization: 2.4796e-08 - loss/weighted_regularization: 1.2398e-08 - loss/image_dissimilarity: -0.6156 - loss/weighted_image_dissimilarity: -0.0616 4/32 [==>...........................] - ETA: 9:24 - loss: -0.0607 - loss/regularization: 5.2380e-08 - loss/weighted_regularization: 2.6190e-08 - loss/image_dissimilarity: -0.6070 - loss/weighted_image_dissimilarity: -0.0607 5/32 [===>..........................] - ETA: 11:01 - loss: -0.0631 - loss/regularization: 8.4857e-08 - loss/weighted_regularization: 4.2429e-08 - loss/image_dissimilarity: -0.6308 - loss/weighted_image_dissimilarity: -0.0631 6/32 [====>.........................] - ETA: 15:03 - loss: -0.0592 - loss/regularization: 1.3120e-07 - loss/weighted_regularization: 6.5598e-08 - loss/image_dissimilarity: -0.5923 - loss/weighted_image_dissimilarity: -0.0592 7/32 [=====>........................] - ETA: 15:59 - loss: -0.0593 - loss/regularization: 1.8052e-07 - loss/weighted_regularization: 9.0259e-08 - loss/image_dissimilarity: -0.5929 - loss/weighted_image_dissimilarity: -0.0593 8/32 [======>.......................] - ETA: 16:29 - loss: -0.0599 - loss/regularization: 2.3676e-07 - loss/weighted_regularization: 1.1838e-07 - loss/image_dissimilarity: -0.5994 - loss/weighted_image_dissimilarity: -0.0599 9/32 [=======>......................] - ETA: 15:46 - loss: -0.0597 - loss/regularization: 3.0428e-07 - loss/weighted_regularization: 1.5214e-07 - loss/image_dissimilarity: -0.5967 - loss/weighted_image_dissimilarity: -0.059710/32 [========>.....................] - ETA: 15:47 - loss: -0.0600 - loss/regularization: 3.6981e-07 - loss/weighted_regularization: 1.8490e-07 - loss/image_dissimilarity: -0.5999 - loss/weighted_image_dissimilarity: -0.060011/32 [=========>....................] - ETA: 15:26 - loss: -0.0592 - loss/regularization: 4.5827e-07 - loss/weighted_regularization: 2.2914e-07 - loss/image_dissimilarity: -0.5916 - loss/weighted_image_dissimilarity: -0.05922020-12-22 17:18:12.922214: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 280, in data_generator
    fixed_image = self.loader_fixed_image.get_data(index=fixed_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


Traceback (most recent call last):
  File "/home/bryanko/venvs/deepreg/bin/deepreg_train", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_train')())
  File "/home/bryanko/DeepReg/deepreg/train.py", line 256, in main
    max_epochs=args.max_epochs,
  File "/home/bryanko/DeepReg/deepreg/train.py", line 177, in train
    callbacks=callbacks,
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 280, in data_generator
    fixed_image = self.loader_fixed_image.get_data(index=fixed_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


	 [[{{node PyFunc}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[div_no_nan_4/ReadVariableOp_1/_56]]
  (1) Unknown:  error: Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 280, in data_generator
    fixed_image = self.loader_fixed_image.get_data(index=fixed_index)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 134, in get_data
    arr = load_nifti_file(file_path=file_path)

  File "/home/bryanko/DeepReg/deepreg/dataset/loader/nifti_loader.py", line 22, in load_nifti_file
    return np.asarray(nib.load(file_path).dataobj, dtype=np.float32)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)

  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)

  File "/share/apps/python-3.7.2-shared/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "/share/apps/python-3.7.2-shared/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)

zlib.error: Error -3 while decompressing data: invalid code lengths set


	 [[{{node PyFunc}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_19649]

Function call stack:
train_function -> train_function

GPU Epilog Script v0.30
